---
title: "Análisis de datos atmosféricos"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instalar paquete S5Processor

```{r}
#devtools::install_github("MBalthasar/S5Processor")
```

## Cargar paquetes

```{r}
library(S5Processor)
library(raster)
library(sf)
library(readr)
library(tidyverse)
```

Cargar datos

```{r, eval=FALSE}
# f <- 'S5P_OFFL_L2__NO2____20190401T171141_20190401T185312_07595_01_010300_20190407T185548.nc'
# f <- 'S5P_OFFL_L2__NO2____20200401T174952_20200401T193122_12788_01_010302_20200403T102954.nc'
f <- 'S5P_NRTI_L2__NO2____20191209T173610_20191209T174110_11170_01_010302_20191209T182308.nc'
nc <- ncdf4::nc_open(f)
vars <- attributes(nc$var)$names
p <- 6
p
ncr <- S5P_process(input = f, product = p)
ncr
```

## Exportar

```{r, eval=FALSE}
writeRaster(ncr, paste0(gsub('.nc', '', f), '_', gsub('/','_', vars[p]), '.tif'), overwrite=T)
```

## Instalar sentinelsat (API de Sentinel)

```{bash, eval=F}
git clone https://github.com/sentinelsat/sentinelsat.git
sudo apt install python-pip
pip install sentinelsat
sudo find / -type f -iname '*sentinelsat*'
/home/mirel/.local/bin/sentinelsat -u s5pguest -p s5pguest -g /home/mirel/Documents/analisis-atmosfericos-mirel/descargas/rd.geojson --sentinel 5 -s 20181018 -e 20191018 --url "https://s5phub.copernicus.eu/dhus" --producttype L2__NO2___
#Footprins y metadatos:
/home/mirel/.local/bin/sentinelsat -u s5pguest -p s5pguest -d -g /home/mirel/Documents/analisis-atmosfericos-mirel/descargas/rd.geojson --sentinel 5 -s 20181018 -e 20181019 --url "https://s5phub.copernicus.eu/dhus" --producttype L2__NO2___ --footprints
#Para descargar, agrega flag -d, ejemplo:
/home/mirel/.local/bin/sentinelsat -u s5pguest -p s5pguest -d -g /home/mirel/Documents/analisis-atmosfericos-mirel/descargas/rd.geojson --sentinel 5 -s 20181018 -e 20181019 --url "https://s5phub.copernicus.eu/dhus" --producttype L2__NO2___
```

# Revisar y descargar pendientes (ejecutar al finalizar la descarga por fecha)

```{r, eval=F}
fp <- st_read('descargas/footprints-20181018-20191018.geojson')
nombrestodos <- gsub('\\.nc', '', fp$filename)
descargados_df <- read_delim('lista-descargas-a-20200210.txt', delim = ' ', col_names = F)
#El archivo "lista-descargas-a-20200210.txt" se genera al ejecutar, en la terminal,
#ls -al > lista-descargas-a-20200210.txt
#dentro de la carpeta donde se encuentren todas las imágenes
descargados <- gsub('\\.zip$', '', grep('^S5P.*', descargados_df$X9, value = T))
match(nombrestodos, descargados)
#N pendientes
length(which(is.na(match(nombrestodos, descargados))))
#Indice pendientes
uuidpendientes <- fp %>%
  slice(which(is.na(match(nombrestodos, descargados)))) %>%
  pull(uuid) %>% as.character()
sapply(
  uuidpendientes,
  function(x) {
    system(
      paste0(
        '/home/mirel/.local/bin/sentinelsat ',
        '--uuid ', x,
        ' -u s5pguest -p s5pguest -d ',
        '-g /home/mirel/Documents/analisis-atmosfericos-mirel/descargas/rd.geojson ',
        '--sentinel 5 ',
        '--url "https://s5phub.copernicus.eu/dhus"'
      )
    )
  }
)
```

